language: java
jdk: oraclejdk7
before_install:
    - git clone https://github.com/mosabua/maven-android-sdk-deployer.git
    - ( cd maven-android-sdk-deployer ; mvn install -P 4.3 )

script: 
    - (cd library && mvn clean install)